version: "3"
services:
  neo4j:
    image: neo4j
    ports:
      - "7474:7474" # browser port
      - "7687:7687"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
