version: "3"
services:
  neo4j:
    image: neo4j # password: neo4jDatabase
    ports:
      - "7474:7474" # browser port
      - "7687:7687"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # mysql:
  #   image: mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=123456
